config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get "tasks/new", to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for task do |f| %>
  <%= f.input :title, input_html: { class: "form-control form-group" } %>
  <%= f.input :details, input_html: { class: "form-control form-group" } %>
  <% unless f.object.new_record? %>
    <%= f.input :completed, type: 'checkbox' %>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/tasks/edit.html.erb
<h3>Edit Task</h3>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h2>My tasks:</h2>
<%= link_to 'Add a new task', tasks_new_path, class: 'add btn btn-warning' %>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        <i class="far fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task.id), class: 'link' %>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h3>New Task</h3>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<br>
<% if @task.completed %>
  <i class="new far fa-check-square">  completed</i>
<% else %>
  <i class="new far fa-square"> not completed</i>
<% end %>
<br>
<%= link_to 'Back to tasks', '/tasks', class: 'link' %>
<%= link_to 'Edit task', edit_path(@task), class: 'link' %>
<%= link_to 'Delete Task', destroy_path(@task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'link' %>